image: debian:10

before_script:
    - apt-get update
    # one package per line to simplify sorting, git diff, etc.
    - >-
        apt-get -y install
        autoconf
        bison
        build-essential
        ccache
        clang
        cmake
        curl
        flex
        gawk
        git
        gperf
        libboost-program-options-dev
        libffi-dev
        libftdi-dev
        libgmp-dev
        libreadline-dev
        mercurial
        pkg-config
        python
        python3
        python3-dev
        python3-keyring
        python3-pip
        python3-setuptools
        python3-venv
        python3-wheel
        tcl-dev
    - export PATH="$HOME/.local/bin:/usr/lib/ccache:$PATH"
    - export CCACHE_BASEDIR="$PWD"
    - export CCACHE_DIR="$PWD/ccache"
    - export CCACHE_COMPILERCHECK=content
    - ccache --zero-stats || true
    - ccache --show-stats || true
    - python3 -m venv --system-site-packages .venv
    - . .venv/bin/activate
    - python3 -m pip install pytest-xdist pytest-cov coverage

    - git clone --depth 1 -b $yosys_version $yosys_url yosys
    - pushd yosys
    - git rev-parse HEAD
    - make config-gcc
    - make -j$(nproc)
    - make install
    - popd
    - yosys -V

    - git clone https://github.com/YosysHQ/sby.git sby
    - pushd sby
    - git checkout de00dc71db618f711976bdee3d9275857849bb99
    - make install
    - popd

    - git clone --depth 1 -b Yices-2.6.4 https://github.com/SRI-CSL/yices2.git yices2
    - pushd yices2
    - autoconf
    - ./configure
    - make -j$(nproc)
    - make install
    - popd

    - git clone --depth 1 -b z3-4.8.17 https://github.com/Z3Prover/z3.git z3
    - pushd z3
    - python scripts/mk_make.py
    - cd build
    - make -j$(nproc)
    - make install
    - popd

build_on_yosys_0.13_with_jny:
    stage: build
    script:
        - . .venv/bin/activate
        - python3 setup.py develop
        - pytest -n auto --cov-report=xml:cov.xml tests --cov 
    variables:
        yosys_version: yosys-0.13-with-write_jny
        yosys_url: https://git.libre-soc.org/git/yosys.git
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: cov.xml

    cache:
        when: always
        paths:
            - ccache
        key: yosys-0-13-with-jny


build_on_yosys_master:
    stage: build
    script:
        - . .venv/bin/activate
        - python3 setup.py develop
        - pytest -n auto --cov-report=xml:cov.xml tests --cov
    variables:
        yosys_version: master
        yosys_url: https://github.com/YosysHQ/yosys.git
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: cov.xml

    cache:
        when: always
        paths:
            - ccache
        key: yosys-master
