dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
cache:
  directories:
    - "$HOME/.local"
    - "$HOME/.cache/wasmtime"
before_install:
  - if ! yices -V; then (git clone https://github.com/SRI-CSL/yices2.git && cd yices2 && autoconf && ./configure --prefix=$HOME/.local && make && make install); fi
  - pip install coverage codecov pyvcd Jinja2 yowasp-yosys nmigen-yosys
  - export NMIGEN_USE_YOSYS=builtin YOSYS=yowasp-yosys
install:
  - python setup.py develop
script:
  - coverage run -m unittest discover
  - codecov
matrix:
  fast_finish: true
